// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var Curry = require("rescript/lib/js/curry.js");

function make(solution, path) {
  console.log(Curry._1(solution, Fs.readFileSync(Path.resolve(__dirname, path), "utf8")));
  
}

exports.make = make;
/* fs Not a pure module */
